In [1]:
import numpy as np 

In [5]:
# boradcasting-arth.op on diff-sized array
a=np.ones([3,3],dtype=int)

In [6]:
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [8]:
b=np.linspace(10,20,3,dtype=int,axis=0)
b


array([10, 15, 20])

In [10]:
broadcast_1=a*b
broadcast_1

array([[10, 15, 20],
       [10, 15, 20],
       [10, 15, 20]])

In [11]:
/*
1 1 1     10 15 20
1 1 1   * 10 15 20 #this small arr brodcasted to greater arr
1 1 1     10 15 20
*/

SyntaxError: invalid syntax (1875680205.py, line 2)

In [18]:
b=np.linspace(2,6,3,dtype=int,endpoint=False,retstep=False,axis=0)
b

array([2, 3, 4])

In [19]:
broadcast_2=a-b
broadcast_2

array([[-1, -2, -3],
       [-1, -2, -3],
       [-1, -2, -3]])

In [20]:
a=np.array([[[5,3]]])
a.ndim

3

In [24]:
b=np.random.randn(2)

In [25]:
b

array([-0.6009718 ,  1.08059244])

In [26]:
a+b

array([[[4.3990282 , 4.08059244]]])

In [27]:
b.ndim
# brodcasted as 1x1x1 until shape get same 

1

In [ ]:
# structrued array

In [31]:
structred_arr=np.array([('gautam',23,45.3),('sayyam',19,42.23),('rakesh',23,56.3)],dtype={'names':('name','age','weight'),'formats':('a10','i4','f8')})

In [32]:
structred_arr

array([(b'gautam', 23, 45.3 ), (b'sayyam', 19, 42.23),
       (b'rakesh', 23, 56.3 )],
      dtype=[('name', 'S10'), ('age', '<i4'), ('weight', '<f8')])

In [33]:
structred_arr[0]

(b'gautam', 23, 45.3)

In [34]:
structred_arr['name']

array([b'gautam', b'sayyam', b'rakesh'], dtype='|S10')

In [40]:
structred_arr.dtype.name

'void176'

In [41]:
structred_arr.dtype.names

('name', 'age', 'weight')

In [ ]:
np.genfromtxt

In [42]:
from io import StringIO


In [50]:
s=StringIO("1,1.3,abcde")

In [51]:
s

In [45]:
data=np.genfromtxt(s,dtype=[('myint','i8'),('myfloat','f4'),('mystrings','S5')],delimiter=',')

In [46]:
data

array((1, 1.3, b'abcde'),
      dtype=[('myint', '<i8'), ('myfloat', '<f4'), ('mystrings', 'S5')])

In [53]:
_=s.seek(0)
# moving ptr to zero position to read string

In [54]:
data=np.genfromtxt(s,dtype='i2,f4,a5',names=['number','float_val','random_str'],delimiter=',')

In [55]:
data

array((1, 1.3, b'abcde'),
      dtype=[('number', '<i2'), ('float_val', '<f4'), ('random_str', 'S5')])

In [58]:
s=StringIO(u"1123.3flog")
data=np.genfromtxt(s,dtype=None,names=['intvar','fltvar','strvar'],delimiter=[3,3,4])

/tmp/ipykernel_4709/314693160.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  data=np.genfromtxt(s,dtype=None,names=['intvar','fltvar','strvar'],delimiter=[3,3,4])


In [59]:
data

array((112, 3.3, b'flog'),
      dtype=[('intvar', '<i8'), ('fltvar', '<f8'), ('strvar', 'S4')])

In [60]:
!touch gent_sample

In [61]:
! echo " text,# of chars hello world,11 numpy,5" >gent_sample

In [62]:
!cat gent_sample

 text,# of chars hello world,11 numpy,5


In [66]:
data=np.genfromtxt('gent_sample',dtype='S12,S12',delimiter=',')

In [67]:
data

array((b'text', b''), dtype=[('f0', 'S12'), ('f1', 'S12')])

In [95]:
abc=np.array([1,2,np.nan,np.nan,3,2])

In [96]:
abc

array([ 1.,  2., nan, nan,  3.,  2.])

In [99]:
abc=np.where(abc==np.nan,abc.mean(),abc)

In [100]:
abc

array([ 1.,  2., nan, nan,  3.,  2.])

In [101]:
abc=np.linspace(5,25,4,endpoint=False)

In [102]:
abc

array([ 5., 10., 15., 20.])

In [103]:
np.tile(abc,2)

array([ 5., 10., 15., 20.,  5., 10., 15., 20.])

In [104]:
np.tile(abc,4)

array([ 5., 10., 15., 20.,  5., 10., 15., 20.,  5., 10., 15., 20.,  5.,
       10., 15., 20.])

In [105]:
np.tile(abc,(2,1))

array([[ 5., 10., 15., 20.],
       [ 5., 10., 15., 20.]])

In [106]:
np.tile(abc,(3,2))

array([[ 5., 10., 15., 20.,  5., 10., 15., 20.],
       [ 5., 10., 15., 20.,  5., 10., 15., 20.],
       [ 5., 10., 15., 20.,  5., 10., 15., 20.]])

In [107]:
np.tile(abc,(2,3,4))

array([[[ 5., 10., 15., 20.,  5., 10., 15., 20.,  5., 10., 15., 20.,
          5., 10., 15., 20.],
        [ 5., 10., 15., 20.,  5., 10., 15., 20.,  5., 10., 15., 20.,
          5., 10., 15., 20.],
        [ 5., 10., 15., 20.,  5., 10., 15., 20.,  5., 10., 15., 20.,
          5., 10., 15., 20.]],

       [[ 5., 10., 15., 20.,  5., 10., 15., 20.,  5., 10., 15., 20.,
          5., 10., 15., 20.],
        [ 5., 10., 15., 20.,  5., 10., 15., 20.,  5., 10., 15., 20.,
          5., 10., 15., 20.],
        [ 5., 10., 15., 20.,  5., 10., 15., 20.,  5., 10., 15., 20.,
          5., 10., 15., 20.]]])

In [108]:
np.unique(abc)
# find unique elements from an array

array([ 5., 10., 15., 20.])

In [109]:
x=np.array([[3,5],[6,3]])
x

array([[3, 5],
       [6, 3]])

In [110]:
np.repeat(x,2)

array([3, 3, 5, 5, 6, 6, 3, 3])

In [111]:
x.ndim

2

In [114]:
np.repeat(x,(2,3),axis=1)
# 2-1st 3-2nd

array([[3, 3, 5, 5, 5],
       [6, 6, 3, 3, 3]])

In [115]:
np.repeat(x,(2,3),axis=0)

array([[3, 5],
       [3, 5],
       [6, 3],
       [6, 3],
       [6, 3]])

In [116]:
x

array([[3, 5],
       [6, 3]])

In [119]:
np.append(x,[[12,11]],axis=0)

array([[ 3,  5],
       [ 6,  3],
       [12, 11]])

In [122]:
np.append(x,[[12,11]],axis=0)

array([[ 3,  5],
       [ 6,  3],
       [12, 11]])

In [123]:
x

array([[3, 5],
       [6, 3]])

In [131]:
y=np.array([[4,5],[6,4]])
np.append(x,y,axis=1)

array([[3, 5, 4, 5],
       [6, 3, 6, 4]])

In [132]:
y.shape

(2, 2)

In [133]:
x.shape

(2, 2)

In [134]:
x

array([[3, 5],
       [6, 3]])

In [136]:
x=np.append(x,[[5,3],[5,2]],axis=0)

In [137]:
np.append(x,[[1],[2],[3],[4]],axis=1)

array([[3, 5, 1],
       [6, 3, 2],
       [5, 3, 3],
       [5, 2, 4]])

In [138]:
x

array([[3, 5],
       [6, 3],
       [5, 3],
       [5, 2]])

In [140]:
np.insert(x,1,11)

array([ 3, 11,  5,  6,  3,  5,  3,  5,  2])

In [141]:
np.insert(x,2,111,axis=1)

array([[  3,   5, 111],
       [  6,   3, 111],
       [  5,   3, 111],
       [  5,   2, 111]])

In [142]:
np.insert(x,1,23,axis=1)

array([[ 3, 23,  5],
       [ 6, 23,  3],
       [ 5, 23,  3],
       [ 5, 23,  2]])

In [143]:
x

array([[3, 5],
       [6, 3],
       [5, 3],
       [5, 2]])

In [146]:
np.insert(x,0,[[11],[22]],axis=1)

array([[11, 22,  3,  5],
       [11, 22,  6,  3],
       [11, 22,  5,  3],
       [11, 22,  5,  2]])

In [147]:
x


array([[3, 5],
       [6, 3],
       [5, 3],
       [5, 2]])

In [148]:
np.delete(x,1,axis=0)

array([[3, 5],
       [5, 3],
       [5, 2]])

In [149]:
np.delete(x,1,axis=1)

array([[3],
       [6],
       [5],
       [5]])

In [150]:
np.full((2,3),8)

array([[8, 8, 8],
       [8, 8, 8]])