In [1]:
import numpy as np

In [2]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [3]:
np.zeros((5,2),dtype=complex)

array([[0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j]])

In [4]:
np.zeros_like?

In [5]:
x=np.arange(6).reshape((2,3))

In [7]:
np.zeros_like(x,dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [8]:
type(x)

numpy.ndarray

In [11]:
x.ndim

2

In [12]:
x.shape

(2, 3)

In [13]:
x.size

6

In [14]:
x.itemsize

8

In [27]:
mylist=[[4,5,3,5],[6,4,7,2]]
list_arr=np.array(mylist,dtype=int)

In [16]:
list_arr

array([[4, 5, 3, 5],
       [6, 4, 7, 2]])

In [18]:
list_arr.dtype

dtype('int64')

In [19]:
list_arr.dtype.name

'int64'

In [20]:
list_arr=np.dtype(float)

In [28]:
list_arr

array([[4, 5, 3, 5],
       [6, 4, 7, 2]])

In [29]:
list_arr=list_arr.astype(np.float32)

In [30]:
list_arr

array([[4., 5., 3., 5.],
       [6., 4., 7., 2.]], dtype=float32)

In [31]:
np.zeros((3,3),dtype=bool)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [33]:
np.ones((3,4),dtype=bool)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [34]:
np.ones_like(list_arr)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [35]:
np.ones_like(list_arr).astype(np.int32)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [36]:
np.arange(10,24,2,dtype=int,like=list_arr)

array([10, 12, 14, 16, 18, 20, 22])

In [37]:
np.arange(10,20,dtype=np.float32).reshape(2,5)

array([[10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]], dtype=float32)

In [39]:
arange=np.arange(10,20,dtype=np.float32).reshape(2,5)
arange=arange.astype(np.int32)
arange.reshape(5,2)

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]], dtype=int32)

In [40]:
np.linspace?

In [41]:
np.linspace(2,5,10)

array([2.        , 2.33333333, 2.66666667, 3.        , 3.33333333,
       3.66666667, 4.        , 4.33333333, 4.66666667, 5.        ])

In [42]:
np.linspace(2,5,10,endpoint=False)

array([2. , 2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7])

In [43]:
np.linspace(2,5,10,endpoint=False,retstep=True)

(array([2. , 2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7]), 0.3)

In [44]:
np.linspace(2,5,10,retstep=True)

(array([2.        , 2.33333333, 2.66666667, 3.        , 3.33333333,
        3.66666667, 4.        , 4.33333333, 4.66666667, 5.        ]),
 0.3333333333333333)

In [45]:
np.random?

In [46]:
np.random.rand(3,2)

array([[0.75943167, 0.10679049],
       [0.78361489, 0.0843463 ],
       [0.05981887, 0.04288097]])

In [47]:
np.random.rand(2,3,dtype=int)

TypeError: rand() got an unexpected keyword argument 'dtype'

In [49]:
ab=np.random.rand(2,3)
ab

array([[0.38160053, 0.3802649 , 0.07436303],
       [0.1928347 , 0.97612444, 0.77479022]])

In [50]:
ab=ab.astype(np.int)

/tmp/ipykernel_3515/4118181218.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  ab=ab.astype(np.int)


In [51]:
ab
# similar to np.zeros or np.zeros_like

array([[0, 0, 0],
       [0, 0, 0]])

In [53]:
np.random.random(3)
# 1-D random arr

array([0.58754071, 0.792106  , 0.15378363])

In [54]:
np.random.randn(2,5)

array([[-1.4569324 ,  2.59299867,  0.45351307,  0.95610785,  1.22883431],
       [-0.65388543, -0.04905635,  0.71948506, -1.44734393, -1.77401466]])

In [56]:
a=np.linspace(4,20,16,dtype=int).reshape(4,4)
a

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 20]])

In [57]:
a+2

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 22]])

In [58]:
a*9

array([[ 36,  45,  54,  63],
       [ 72,  81,  90,  99],
       [108, 117, 126, 135],
       [144, 153, 162, 180]])

In [59]:
a/.5

array([[ 8., 10., 12., 14.],
       [16., 18., 20., 22.],
       [24., 26., 28., 30.],
       [32., 34., 36., 40.]])

In [60]:
a//.5

array([[ 8., 10., 12., 14.],
       [16., 18., 20., 22.],
       [24., 26., 28., 30.],
       [32., 34., 36., 40.]])

In [61]:
a%2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 0]])

In [63]:
np.sin(a)

array([[-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.91294525]])

In [64]:
a*np.sin(a)

array([[ -3.02720998,  -4.79462137,  -1.67649299,   4.59890619],
       [  7.91486597,   3.70906637,  -5.44021111, -10.99989227],
       [ -6.43887502,   5.46217148,  13.86850298,   9.7543176 ],
       [ -4.60645307, -16.34375736, -13.51777044,  18.25890501]])

In [65]:
a

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 20]])

In [67]:
np.asarray(a) is a

True

In [68]:
b=[35.35,35,34]

In [69]:
np.asarray(b) is b
#bcuz it's a list

False

In [70]:
np.empty?

In [74]:
b=np.empty([2,2])

In [75]:
b.fill(4) # fill empty arr

In [79]:
b.fill(4)

In [80]:
b=b.astype(np.int32)

In [81]:
b

array([[4, 4],
       [4, 4]], dtype=int32)

In [82]:
a

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 20]])

In [83]:
b=np.empty([4,4],dtype=int)

In [84]:
b

array([[4613999089671741102, 4617084282184949696, 4610229072374068256,
        4616863926479448263],
       [4620597365289045883, 4615534493754570115, 4617811151608095526,
        4622382006896952754],
       [4618935547208079480, 4617835876786466837, 4623996891161219708,
        4621680810694661818],
       [4616872423505993976, 4625293576404949079, 4623799446295380459,
        4625832642545862156]])

In [85]:
b.fill(3)

In [86]:
b

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [87]:
a.dot(b)
# matrix multiplication

array([[ 66,  66,  66,  66],
       [114, 114, 114, 114],
       [162, 162, 162, 162],
       [213, 213, 213, 213]])

In [88]:
np.dot(a,b)

array([[ 66,  66,  66,  66],
       [114, 114, 114, 114],
       [162, 162, 162, 162],
       [213, 213, 213, 213]])

In [89]:
1.5*a
# scaler multiplication

array([[ 6. ,  7.5,  9. , 10.5],
       [12. , 13.5, 15. , 16.5],
       [18. , 19.5, 21. , 22.5],
       [24. , 25.5, 27. , 30. ]])

In [90]:
a+=2

In [94]:
a

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 24]])

In [95]:
a+=2

In [96]:
a

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 26]])

In [97]:
a*=2
a

array([[20, 22, 24, 26],
       [28, 30, 32, 34],
       [36, 38, 40, 42],
       [44, 46, 48, 52]])

In [98]:
a*b

array([[ 60,  66,  72,  78],
       [ 84,  90,  96, 102],
       [108, 114, 120, 126],
       [132, 138, 144, 156]])

In [99]:
b

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [100]:
np.sqrt(a)

array([[4.47213595, 4.69041576, 4.89897949, 5.09901951],
       [5.29150262, 5.47722558, 5.65685425, 5.83095189],
       [6.        , 6.164414  , 6.32455532, 6.4807407 ],
       [6.63324958, 6.78232998, 6.92820323, 7.21110255]])

In [101]:
np.sqrt(b)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [1.73205081, 1.73205081, 1.73205081, 1.73205081]])

In [102]:
np.square(b)

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [103]:
np.square(a)

array([[ 400,  484,  576,  676],
       [ 784,  900, 1024, 1156],
       [1296, 1444, 1600, 1764],
       [1936, 2116, 2304, 2704]])

In [104]:
np.mod?

TypeError: remainder() takes from 2 to 3 positional arguments but 1 were given

In [105]:
np.mod(a,4)

array([[0, 2, 0, 2],
       [0, 2, 0, 2],
       [0, 2, 0, 2],
       [0, 2, 0, 0]])

In [106]:
a

array([[20, 22, 24, 26],
       [28, 30, 32, 34],
       [36, 38, 40, 42],
       [44, 46, 48, 52]])

In [107]:
np.mod(a,3)

array([[2, 1, 0, 2],
       [1, 0, 2, 1],
       [0, 2, 1, 0],
       [2, 1, 0, 1]])

In [108]:
np.remainder(a,4)
#np.remainder and np.mod both are same

array([[0, 2, 0, 2],
       [0, 2, 0, 2],
       [0, 2, 0, 2],
       [0, 2, 0, 0]])

In [109]:
np.modf?

In [110]:
fract,intergral=np.modf(a)

In [111]:
fract

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [112]:
intergral

array([[20., 22., 24., 26.],
       [28., 30., 32., 34.],
       [36., 38., 40., 42.],
       [44., 46., 48., 52.]])

In [117]:
np.modf(a)

(array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 array([[20., 22., 24., 26.],
        [28., 30., 32., 34.],
        [36., 38., 40., 42.],
        [44., 46., 48., 52.]]))

In [118]:
np.divmod(a,3)
# return quotient and remainder

(array([[ 6,  7,  8,  8],
        [ 9, 10, 10, 11],
        [12, 12, 13, 14],
        [14, 15, 16, 17]]),
 array([[2, 1, 0, 2],
        [1, 0, 2, 1],
        [0, 2, 1, 0],
        [2, 1, 0, 1]]))

In [119]:
np.divmod(a,4)

(array([[ 5,  5,  6,  6],
        [ 7,  7,  8,  8],
        [ 9,  9, 10, 10],
        [11, 11, 12, 13]]),
 array([[0, 2, 0, 2],
        [0, 2, 0, 2],
        [0, 2, 0, 2],
        [0, 2, 0, 0]]))

In [120]:
a

array([[20, 22, 24, 26],
       [28, 30, 32, 34],
       [36, 38, 40, 42],
       [44, 46, 48, 52]])

In [121]:
a.max()

52

In [123]:
np.max(a)

52

In [124]:
np.mean(a)

35.125

In [125]:
np.median(a)

35.0

In [126]:
np.std(a)

9.433152972362953

In [127]:
np.var(a)

88.984375

In [128]:
np.eye?

In [129]:
np.eye(2,3,k=0)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [130]:
np.eye(3,3,k=0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [131]:
np.eye(3,3,k=1,dtype=int)

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [132]:
np.eye(3,3,k=-1,dtype=int)

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0]])

In [133]:
a

array([[20, 22, 24, 26],
       [28, 30, 32, 34],
       [36, 38, 40, 42],
       [44, 46, 48, 52]])

In [136]:
np.eye(a.shape[0],a.shape[1],dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [137]:
list_arr

array([[4., 5., 3., 5.],
       [6., 4., 7., 2.]], dtype=float32)

In [141]:
list_arr=[4,5,3,5,325,23,23,5]
type(list_arr)
len(list_arr)

8

In [142]:
np.asarray(list_arr).reshape(2,4)

array([[  4,   5,   3,   5],
       [325,  23,  23,   5]])

In [143]:
np.identity?


In [149]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [151]:
np.identity(a.shape[0],like=a)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [152]:
a

array([[20, 22, 24, 26],
       [28, 30, 32, 34],
       [36, 38, 40, 42],
       [44, 46, 48, 52]])

In [153]:
np.mean(a,axis=1)

array([23. , 31. , 39. , 47.5])

In [154]:
np.mean(a,axis=0)

array([32. , 34. , 36. , 38.5])

In [155]:
np.sum(a,axis=1,dtype=int)

array([ 92, 124, 156, 190])

In [156]:
np.sum(a)

562

In [158]:
np.sum(a,axis=0,dtype=int)

array([128, 136, 144, 154])

In [159]:
np.cumsum(a,axis=1,dtype=int)

array([[ 20,  42,  66,  92],
       [ 28,  58,  90, 124],
       [ 36,  74, 114, 156],
       [ 44,  90, 138, 190]])

In [160]:
np.cumsum(a,axis=0,dtype=int)

array([[ 20,  22,  24,  26],
       [ 48,  52,  56,  60],
       [ 84,  90,  96, 102],
       [128, 136, 144, 154]])

In [162]:
a.cumprod(axis=1)

array([[     20,     440,   10560,  274560],
       [     28,     840,   26880,  913920],
       [     36,    1368,   54720, 2298240],
       [     44,    2024,   97152, 5051904]])

In [163]:
a.cumprod(axis=0)

array([[     20,      22,      24,      26],
       [    560,     660,     768,     884],
       [  20160,   25080,   30720,   37128],
       [ 887040, 1153680, 1474560, 1930656]])

In [164]:
np.maximum(a,b)

array([[20, 22, 24, 26],
       [28, 30, 32, 34],
       [36, 38, 40, 42],
       [44, 46, 48, 52]])

In [165]:
a

array([[20, 22, 24, 26],
       [28, 30, 32, 34],
       [36, 38, 40, 42],
       [44, 46, 48, 52]])

In [166]:
b

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [167]:
a.min()

20

In [171]:
~np.maximum(a,b)

array([[-21, -23, -25, -27],
       [-29, -31, -33, -35],
       [-37, -39, -41, -43],
       [-45, -47, -49, -53]])

In [172]:
np.minimum(a,b)

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [173]:
np.minimum?

In [174]:
a>30

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [175]:
a[a>30]

array([32, 34, 36, 38, 40, 42, 44, 46, 48, 52])

In [180]:
len(a[a>30])

10

In [181]:
len(a[a<30])

5

In [182]:
a[a<30]

array([20, 22, 24, 26, 28])

In [183]:
np.where?

In [184]:
a

array([[20, 22, 24, 26],
       [28, 30, 32, 34],
       [36, 38, 40, 42],
       [44, 46, 48, 52]])

In [185]:
np.where(a>32,-1,1)

array([[ 1,  1,  1,  1],
       [ 1,  1,  1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1]])

In [186]:
tem=np.random.randn(3,3)

In [187]:
tem

array([[ 1.46393409,  0.9001728 , -0.53902762],
       [ 0.23875801, -0.18807383, -1.37509966],
       [ 0.21476076, -1.56072698,  0.95224918]])

In [192]:
np.where(tem<0,tem*-2,tem)

array([[1.46393409, 0.9001728 , 1.07805524],
       [0.23875801, 0.37614766, 2.75019932],
       [0.21476076, 3.12145396, 0.95224918]])

In [193]:
a


array([[20, 22, 24, 26],
       [28, 30, 32, 34],
       [36, 38, 40, 42],
       [44, 46, 48, 52]])

In [194]:
b

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [195]:
b=np.random.randint(3,30)

In [196]:
b

7

In [197]:
b=np.asarray(np.random.randn())

In [198]:
b

array(-0.86930809)

In [206]:
b=np.linspace(-1,50,16,dtype=int).reshape(4,4)

In [207]:
b+=12

In [210]:
a

array([[20, 22, 24, 26],
       [28, 30, 32, 34],
       [36, 38, 40, 42],
       [44, 46, 48, 52]])

In [211]:
b

array([[11, 14, 17, 21],
       [24, 28, 31, 34],
       [38, 41, 45, 48],
       [51, 55, 58, 62]])

In [213]:
np.where(a>b,'a' ,'b')

array([['a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'b'],
       ['b', 'b', 'b', 'b'],
       ['b', 'b', 'b', 'b']], dtype='<U1')

In [214]:
a=a.T
a

array([[20, 28, 36, 44],
       [22, 30, 38, 46],
       [24, 32, 40, 48],
       [26, 34, 42, 52]])

In [217]:
np.swapaxes(a,1,0)

array([[20, 22, 24, 26],
       [28, 30, 32, 34],
       [36, 38, 40, 42],
       [44, 46, 48, 52]])

In [218]:
np.swapaxes

<function numpy.swapaxes(a, axis1, axis2)>

In [219]:
tem=np.random.randn(3,5)

In [220]:
tem

array([[ 0.09758942,  0.38849561, -0.13295625, -2.1958337 , -2.32416306],
       [-0.93652866, -0.04851154, -0.36623375,  0.33586825, -0.67786797],
       [ 0.159221  ,  1.3172709 ,  0.59533839,  0.43592718, -0.61656015]])

In [221]:
tem.sort()

In [222]:
tem

array([[-2.32416306, -2.1958337 , -0.13295625,  0.09758942,  0.38849561],
       [-0.93652866, -0.67786797, -0.36623375, -0.04851154,  0.33586825],
       [-0.61656015,  0.159221  ,  0.43592718,  0.59533839,  1.3172709 ]])

In [226]:
tem.sort(axis=1)

In [227]:
tem

array([[-2.32416306, -2.1958337 , -0.36623375, -0.04851154,  0.33586825],
       [-0.93652866, -0.67786797, -0.13295625,  0.09758942,  0.38849561],
       [-0.61656015,  0.159221  ,  0.43592718,  0.59533839,  1.3172709 ]])

In [229]:
np.unique(tem)

array([-2.32416306, -2.1958337 , -0.93652866, -0.67786797, -0.61656015,
       -0.36623375, -0.13295625, -0.04851154,  0.09758942,  0.159221  ,
        0.33586825,  0.38849561,  0.43592718,  0.59533839,  1.3172709 ])

In [230]:
!mv /home/agua2de/numpy_arr.npy /home/agua2de/Desktop/numpy/

In [231]:
!ls

numpy_arr.npy  numpy_practice_1.ipynb


In [232]:
load=np.load('numpy_arr.npy')

In [233]:
load

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [234]:
np.any(load)
# if single element is True or True_valued

True

In [235]:
np.all(load)
# if all elements are True or True_values i.e except than 0

False

In [236]:
np.sin([[1,4,2],[5,3,5]])

array([[ 0.84147098, -0.7568025 ,  0.90929743],
       [-0.95892427,  0.14112001, -0.95892427]])

In [237]:
np.arcsin([[1,4,2],[5,3,5]])

/tmp/ipykernel_3515/1565107748.py:1: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin([[1,4,2],[5,3,5]])


array([[1.57079633,        nan,        nan],
       [       nan,        nan,        nan]])

In [238]:
np.cos([[1,4,2],[5,3,5]])

array([[ 0.54030231, -0.65364362, -0.41614684],
       [ 0.28366219, -0.9899925 ,  0.28366219]])

In [239]:
np.tan([[1,4,2],[5,3,5]])


array([[ 1.55740772,  1.15782128, -2.18503986],
       [-3.38051501, -0.14254654, -3.38051501]])

In [240]:
np.tanh([[1,4,2],[5,3,5]])

array([[0.76159416, 0.9993293 , 0.96402758],
       [0.9999092 , 0.99505475, 0.9999092 ]])

In [246]:
my3d=np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [247]:
my3d.shape

(2, 2, 2)

In [248]:
my3d.ndim

3

In [249]:
my3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [250]:
my3d.T

array([[[1, 5],
        [3, 7]],

       [[2, 6],
        [4, 8]]])

In [252]:
my3d.swapaxes(2,1)

array([[[1, 3],
        [2, 4]],

       [[5, 7],
        [6, 8]]])

In [253]:
my3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [254]:
a

array([[20, 28, 36, 44],
       [22, 30, 38, 46],
       [24, 32, 40, 48],
       [26, 34, 42, 52]])

In [255]:
a.ndim

2

In [256]:
a[-1]

array([26, 34, 42, 52])

In [264]:
a[-1,-1]
# a[-1,-1] is equivalent to a[-1][-1]


52

In [265]:
a[-1][-1]

52

In [259]:
a[[-1,2,-3]]

array([[26, 34, 42, 52],
       [24, 32, 40, 48],
       [22, 30, 38, 46]])

In [260]:
a[[-1,1],[2,-1]]

array([42, 46])

In [263]:
a[[1,2],[1,2]]

array([30, 40])

In [268]:
a

array([[20, 28, 36, 44],
       [22, 30, 38, 46],
       [24, 32, 40, 48],
       [26, 34, 42, 52]])

In [269]:
a[:3]

array([[20, 28, 36, 44],
       [22, 30, 38, 46],
       [24, 32, 40, 48]])

In [270]:
a[::2]

array([[20, 28, 36, 44],
       [24, 32, 40, 48]])

In [271]:
a[-3:-1]

array([[22, 30, 38, 46],
       [24, 32, 40, 48]])

In [272]:
a[-3]

array([22, 30, 38, 46])

In [273]:
a[-3:]

array([[22, 30, 38, 46],
       [24, 32, 40, 48],
       [26, 34, 42, 52]])

In [274]:
a[:2,]

array([[20, 28, 36, 44],
       [22, 30, 38, 46]])

In [275]:
a[:2,2:]

array([[36, 44],
       [38, 46]])

In [276]:
a[::2,:]

array([[20, 28, 36, 44],
       [24, 32, 40, 48]])

In [277]:
a

array([[20, 28, 36, 44],
       [22, 30, 38, 46],
       [24, 32, 40, 48],
       [26, 34, 42, 52]])

In [279]:
a[2:,1:3]

array([[32, 40],
       [34, 42]])

In [282]:
a

array([[20, 28, 36, 44],
       [22, 30, 38, 46],
       [24, 32, 40, 48],
       [26, 34, 42, 52]])

In [285]:
for i in a:
    print(i)

[20 28 36 44]
[22 30 38 46]
[24 32 40 48]
[26 34 42 52]


In [287]:
for i in a.flat:
    print(i)

20
28
36
44
22
30
38
46
24
32
40
48
26
34
42
52


In [292]:
my3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [293]:
my3d[1]

array([[5, 6],
       [7, 8]])

In [294]:
my3d[0]


array([[1, 2],
       [3, 4]])

In [295]:
my3d[0][0,0]
# [0][0,0] nd [0],[0],[0] both are same

1

In [296]:
my3d[0][0][0]

1

In [300]:
my3d[1][:,1:]

array([[6],
       [8]])

In [303]:
np.max(a,axis=1)

array([44, 46, 48, 52])

In [304]:
np.apply_along_axis(np.max,axis=1,arr=a)

array([44, 46, 48, 52])

In [307]:
np.apply_along_axis(np.max,axis=1,arr=my3d)

array([[3, 4],
       [7, 8]])

In [306]:
my3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [308]:
np.max(my3d)

8

In [309]:
np.apply_along_axis(np.max,axis=0,arr=my3d)

array([[5, 6],
       [7, 8]])

In [310]:
np.apply_along_axis(np.max,axis=2,arr=my3d)

array([[2, 4],
       [6, 8]])

In [311]:
np.mean(my3d)

4.5

In [312]:
np.mean(my3d,axis=1)

array([[2., 3.],
       [6., 7.]])

In [313]:
my3d.shape

(2, 2, 2)

In [314]:
arr=[np.random.randn(3,4) for _ in range(10)]

In [315]:
arr

[array([[ 1.04840176,  1.22014154,  0.05258707, -0.78600665],
        [ 0.36120248, -0.65314064,  0.17176327,  1.77574749],
        [ 1.33683961, -1.07823891,  0.45805564,  0.65280934]]),
 array([[ 0.82429062, -0.61693891, -0.44776408, -0.59272799],
        [-1.11982094,  0.40863729, -0.84191067,  0.50506578],
        [-1.95038969,  0.38680411, -1.57143217, -0.11358419]]),
 array([[-0.45935942,  1.75761774, -1.03059438, -0.42452365],
        [ 1.09437934,  0.66385141,  0.63719812,  2.09737888],
        [-0.13325686, -1.72847664,  0.81537726, -1.16489748]]),
 array([[ 0.5912941 ,  0.56317681,  0.47126566, -0.10974426],
        [ 0.1762116 , -1.39542089, -0.3036554 , -0.82183026],
        [ 0.8764222 ,  0.84099932,  1.53139211,  1.2515102 ]]),
 array([[ 0.62209762,  0.66625961,  2.31741553,  1.92620863],
        [-0.11805424, -1.17733996,  0.76647935,  1.3685942 ],
        [ 1.37571577, -0.14380912,  2.72326958,  0.69582197]]),
 array([[-0.39817846, -0.02915549, -0.07050669,  1.3089551 ]

In [348]:
a=np.array([_ for _ in range(10) if _%2==0])

In [349]:
a

array([0, 2, 4, 6, 8])

In [350]:
b=np.array([_ for _ in range(13) if _%3==0])

In [351]:
b

array([ 0,  3,  6,  9, 12])

In [353]:
np.stack((a,b))

array([[ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12]])

In [355]:
np.stack((a,b),axis=1)

array([[ 0,  0],
       [ 2,  3],
       [ 4,  6],
       [ 6,  9],
       [ 8, 12]])

In [356]:
np.vstack((a,b))

array([[ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12]])

In [357]:
np.hstack((a,b))

array([ 0,  2,  4,  6,  8,  0,  3,  6,  9, 12])

In [363]:
a,b,c=np.linspace(1,5,10),np.linspace(5,10,10),np.linspace(10,15,10,endpoint=False,dtype=int)

In [364]:
a

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [365]:
b

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [366]:
c

array([10, 10, 11, 11, 12, 12, 13, 13, 14, 14])

In [367]:
np.column_stack((a,b))

array([[ 1.        ,  5.        ],
       [ 1.44444444,  5.55555556],
       [ 1.88888889,  6.11111111],
       [ 2.33333333,  6.66666667],
       [ 2.77777778,  7.22222222],
       [ 3.22222222,  7.77777778],
       [ 3.66666667,  8.33333333],
       [ 4.11111111,  8.88888889],
       [ 4.55555556,  9.44444444],
       [ 5.        , 10.        ]])

In [368]:
np.column_stack((b,c))

array([[ 5.        , 10.        ],
       [ 5.55555556, 10.        ],
       [ 6.11111111, 11.        ],
       [ 6.66666667, 11.        ],
       [ 7.22222222, 12.        ],
       [ 7.77777778, 12.        ],
       [ 8.33333333, 13.        ],
       [ 8.88888889, 13.        ],
       [ 9.44444444, 14.        ],
       [10.        , 14.        ]])

In [369]:
np.count_nonzero(a)
# count number of non-zero values in array

10

In [370]:
np.row_stack((a,b,c))

array([[ 1.        ,  1.44444444,  1.88888889,  2.33333333,  2.77777778,
         3.22222222,  3.66666667,  4.11111111,  4.55555556,  5.        ],
       [ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
         7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ],
       [10.        , 10.        , 11.        , 11.        , 12.        ,
        12.        , 13.        , 13.        , 14.        , 14.        ]])

In [371]:
np.row_stack((b,c))

array([[ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
         7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ],
       [10.        , 10.        , 11.        , 11.        , 12.        ,
        12.        , 13.        , 13.        , 14.        , 14.        ]])

In [372]:
np.concatenate?


In [373]:
a

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [374]:
b

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [375]:
c

array([10, 10, 11, 11, 12, 12, 13, 13, 14, 14])

In [377]:
np.concatenate((a,c),axis=0)

array([ 1.        ,  1.44444444,  1.88888889,  2.33333333,  2.77777778,
        3.22222222,  3.66666667,  4.11111111,  4.55555556,  5.        ,
       10.        , 10.        , 11.        , 11.        , 12.        ,
       12.        , 13.        , 13.        , 14.        , 14.        ])

In [380]:
np.concatenate((b,c))

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ,
       10.        , 10.        , 11.        , 11.        , 12.        ,
       12.        , 13.        , 13.        , 14.        , 14.        ])

In [381]:
a=np.arange(25).reshape(5,5)

In [382]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [383]:
a.ravel

<function ndarray.ravel>

In [385]:
np.ravel(a)
# convt multi. arr to 1-D arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [386]:
np.ravel(a,order='F')

array([ 0,  5, 10, 15, 20,  1,  6, 11, 16, 21,  2,  7, 12, 17, 22,  3,  8,
       13, 18, 23,  4,  9, 14, 19, 24])

In [388]:
np.ravel(a,order='C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [389]:
np.ravel(a,order='A')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [390]:
np.ravel(a,order='K')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [391]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [392]:
a.reshape(-1)
# np.ravel(a) is equivalent to a.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [393]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [394]:
a.flatten(order='C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [395]:
a.flatten(order='F')
# flatten and revel both are same

array([ 0,  5, 10, 15, 20,  1,  6, 11, 16, 21,  2,  7, 12, 17, 22,  3,  8,
       13, 18, 23,  4,  9, 14, 19, 24])

In [396]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [398]:
np.split(a,[1,3])

[array([[0, 1, 2, 3, 4]]),
 array([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])]

In [399]:
np.split(a,[1,3],axis=0)

[array([[0, 1, 2, 3, 4]]),
 array([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])]

In [400]:
np.split(a,[2,4],axis=0)
# split by row-wise

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24]])]

In [401]:
np.split(a,[2,4],axis=1)
#split by column-wise

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16],
        [20, 21]]),
 array([[ 2,  3],
        [ 7,  8],
        [12, 13],
        [17, 18],
        [22, 23]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24]])]

In [402]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [403]:
[x,y,z]=np.split(a,[2,4],axis=1)

In [404]:
x

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21]])

In [405]:
y

array([[ 2,  3],
       [ 7,  8],
       [12, 13],
       [17, 18],
       [22, 23]])

In [406]:
z

array([[ 4],
       [ 9],
       [14],
       [19],
       [24]])

In [407]:
x.ndim

2

In [408]:
type(x)

numpy.ndarray

In [411]:
np.split(my3d,[0,1],axis=1)
# split 3d arr

[array([], shape=(2, 0, 2), dtype=int64),
 array([[[1, 2]],
 
        [[5, 6]]]),
 array([[[3, 4]],
 
        [[7, 8]]])]

In [410]:
my3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [413]:
np.split(my3d,[0,1])

[array([], shape=(0, 2, 2), dtype=int64),
 array([[[1, 2],
         [3, 4]]]),
 array([[[5, 6],
         [7, 8]]])]

In [415]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [416]:
np.hsplit(a,[3])
# split by column

[array([[ 0,  1,  2],
        [ 5,  6,  7],
        [10, 11, 12],
        [15, 16, 17],
        [20, 21, 22]]),
 array([[ 3,  4],
        [ 8,  9],
        [13, 14],
        [18, 19],
        [23, 24]])]

In [418]:
np.vsplit(a,[2,4])
# split by row

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24]])]

In [419]:
np.vsplit(my3d,[0])

[array([], shape=(0, 2, 2), dtype=int64),
 array([[[1, 2],
         [3, 4]],
 
        [[5, 6],
         [7, 8]]])]

In [420]:
np.vsplit(my3d,[1])

[array([[[1, 2],
         [3, 4]]]),
 array([[[5, 6],
         [7, 8]]])]

In [422]:
np.savez('compressed_arr',a=a,b=my3d)

In [423]:
!ls

compressed_arr.npz  numpy_arr.npy  numpy_practice_1.ipynb


In [424]:
load=np.load('compressed_arr.npz')

In [425]:
load

In [429]:
load['a']

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [430]:
load['b']

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [434]:
np.savetxt('test_file.out',a,delimiter=',')

In [441]:
np.loadtxt('test_file.out',delimiter=',',dtype=np.int32)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]], dtype=int32)

In [442]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [443]:
copied_a=a.copy()
# correct way to copy ndarray

In [444]:
copied_a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [446]:
copied_a2=a.copy(order='F')

In [447]:
copied_a2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [448]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [449]:
a.fill(0)

In [450]:
a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [451]:
copied_a
# even data changed from original ndarr ,copied arr remain unchanged

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])