In [1]:
import numpy as np

In [2]:
x=np.array([[2,5,np.nan],[6,np.nan,np.nan]])

In [3]:
x

array([[ 2.,  5., nan],
       [ 6., nan, nan]])

In [4]:
np.nan_to_num(x)

array([[2., 5., 0.],
       [6., 0., 0.]])

In [5]:
x

array([[ 2.,  5., nan],
       [ 6., nan, nan]])

In [7]:
np.nan_to_num(x,nan=111)

array([[  2.,   5., 111.],
       [  6., 111., 111.]])

In [15]:
x[0][0]

2.0

In [16]:
np.nan_to_num(x,nan=x[0][0])

array([[2., 5., 2.],
       [6., 2., 2.]])

In [17]:
np.tile
# repeat arr

<function numpy.tile(A, reps)>

In [18]:
myList=[[5,3,63],[54,3,54]]
myList

[[5, 3, 63], [54, 3, 54]]

In [22]:
x=np.asarray(myList,dtype={'names':('listint1','listint2'),'formats':('i4','i4')})

In [23]:
x

array([[( 5,  5), ( 3,  3), (63, 63)],
       [(54, 54), ( 3,  3), (54, 54)]],
      dtype=[('listint1', '<i4'), ('listint2', '<i4')])

In [24]:
x.dtype.names

('listint1', 'listint2')

In [28]:
x.astype((np.int64,np.int64))

TypeError: Cannot cast array data from dtype([('listint1', '<i4'), ('listint2', '<i4')]) to dtype('int64') according to the rule 'unsafe'

In [ ]:
np.eye